#!/usr/bin/env python3
"""Controlled Spanish localization for ACTA document-card metadata.

Continuity records retain source-control wording, which is often an English
scalar.  Event pages must not silently reuse those scalars in Spanish cards.
This module supplies an exact, reviewable translation table and preserves only
whole-value proper names or stable acronyms as language-neutral terms.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
CONTINUITY = REPO / "evidence/community/actas/event-family-continuity-v1.json"
LOCALIZED_FIELDS = (
    "document_type",
    "issuer_sender",
    "stated_capacity",
    "recipients",
    "meeting_body_if_any",
    "documented_convener",
    "source_provenance_status",
    "public_private_status",
    "unresolved_evidential_issues",
    "no_page_reason",
)

# Only a complete value that is a canonical name, acronym or stable legal label
# may pass unchanged. Phrases containing a name still require translation.
STABLE_NAMES_OR_TERMS = {
    "AEAT",
    "CEXP",
    "Jonathan Simó",
    "Pamanil",
}

CONTROLLED_PHRASE_FIELDS = {
    "source_provenance_status",
    "unresolved_evidential_issues",
}

# Ordered by length at application time. These rules localize the long,
# source-specific provenance/open-issue sentences while retaining stable names,
# hashes, case numbers and file-format labels verbatim.
PHRASE_ES = {
    "material equivalence, provenance/authenticity and official-book relation remain open unless separately stated": "la equivalencia material, la procedencia/autenticidad y la relación con el libro oficial siguen abiertas salvo indicación separada",
    "original books, officeholder files, all custodians and deleted/outside systems remain unsearched or incomplete; absence is not nonexistence": "los libros originales, archivos de cargos, todos los custodios y sistemas eliminados/externos siguen sin buscarse o incompletos; la ausencia no equivale a inexistencia",
    "exact procedural classification, author/issuer, filing/service context and relationship to the ACTA remain unresolved": "la clasificación procesal exacta, autor/emisor, contexto de presentación/notificación y relación con el ACTA siguen sin resolverse",
    "complete original recipient/service denominator unresolved": "denominador completo original de destinatarios/notificación no resuelto",
    "complete certified source control incomplete": "control completo de fuente certificada incompleto",
    "complete certified record incomplete": "registro certificado completo incompleto",
    "complete source record incomplete": "registro completo de fuente incompleto",
    "complete litigation chain incomplete": "cadena litigiosa completa incompleta",
    "complete filing chain incomplete": "cadena completa de presentación incompleta",
    "complete reliance chain incomplete": "cadena completa de uso incompleta",
    "full intake/reliance chain incomplete": "cadena completa de entrada/uso incompleta",
    "complete implementation chain missing": "cadena completa de ejecución ausente",
    "public package status is governed by the linked event manifest": "el estado del paquete público se rige por el manifiesto enlazado del evento",
    "located control source/derivative": "fuente/derivado de control localizado",
    "control copy publicly digitised": "copia de control digitalizada públicamente",
    "public redacted digitisation": "digitalización pública redactada",
    "direct contemporaneous email and attachments located": "correo contemporáneo directo y adjuntos localizados",
    "direct contemporaneous email located": "correo contemporáneo directo localizado",
    "direct correspondence and attachments located": "correspondencia directa y adjuntos localizados",
    "direct email and attachment families located": "correo directo y familias de adjuntos localizados",
    "native report and spreadsheet/email workstream located": "informe nativo y línea de hoja de cálculo/correo localizados",
    "native DOCX and review correspondence located": "DOCX nativo y correspondencia de revisión localizados",
    "verified direct contemporaneous email": "correo contemporáneo directo verificado",
    "primary correspondence located": "correspondencia primaria localizada",
    "primary instrument located": "instrumento primario localizado",
    "signed/stamped primary notice located": "convocatoria primaria firmada/sellada localizada",
    "signed primary report located": "informe primario firmado localizado",
    "primary CEXP cession/statutes instrument located": "instrumento primario de cesión/estatutos CEXP localizado",
    "only a later recital in the 2022 ACTA is located": "sólo se localiza una mención posterior en el ACTA de 2022",
    "only later recital in 2022 ACTA located": "sólo se localiza una mención posterior en el ACTA de 2022",
    "standalone 2018 source missing": "fuente autónoma de 2018 ausente",
    "no Community ACTA located in the finite searched universe": "no se localizó ACTA comunitaria en el universo finito buscado",
    "referenced by ACTA/source family": "referido por el ACTA/la familia fuente",
    "standalone original not located": "original autónomo no localizado",
    "source family exists and later actors cite the meeting": "la familia fuente existe y actores posteriores citan la reunión",
    "controlled tax registers": "registros tributarios controlados",
    "tax secrecy": "secreto tributario",
    "located Drive/email custody family": "familia de custodia Drive/correo localizada",
    "package control hash verified": "hash de control del paquete verificado",
    "located multi-copy source family": "familia fuente multicopia localizada",
    "located Drive copy A": "copia A de Drive localizada",
    "located five-page package control copy B": "copia B de control del paquete de cinco páginas localizada",
    "located nine-page later-transmission control copy": "copia de control de transmisión posterior de nueve páginas localizada",
    "located six-page partial variant": "variante parcial de seis páginas localizada",
    "recovered four-page email-attachment working copy": "copia de trabajo recuperada de cuatro páginas adjunta a correo",
    "recovered four-page working copy": "copia de trabajo recuperada de cuatro páginas",
    "partial three-page sibling binary": "binario hermano parcial de tres páginas",
    "located six-page copy A/control copy": "copia A/de control de seis páginas localizada",
    "located transmitted six-page attachment family B": "familia B transmitida de adjunto de seis páginas localizada",
    "third separately hashed six-page scan": "tercer escaneo de seis páginas con hash separado",
    "located sixteen-page copy A": "copia A de dieciséis páginas localizada",
    "located sixteen-page control copy B": "copia B de control de dieciséis páginas localizada",
    "located transmitted attachment family C": "familia C de adjunto transmitido localizada",
    "separately hashed PDF24/order-and-annotation variant": "variante PDF24/de orden y anotación con hash separado",
    "located one-page proxy associated with notice": "poder de una página asociado a convocatoria localizado",
    "located twenty-one-page Owners' Community control copy": "copia de control comunitaria de veintiuna páginas localizada",
    "located three-page CEXP working export": "exportación de trabajo CEXP de tres páginas localizada",
    "actual three-page public-package control binary": "binario real de control del paquete público de tres páginas",
    "second 90,821-byte conversion": "segunda conversión de 90.821 bytes",
    "located four-page procedural extract A": "extracto procesal A de cuatro páginas localizado",
    "located four-page Bandama-labelled procedural extract B": "extracto procesal B de cuatro páginas rotulado Bandama localizado",
    "located thirty-eight-page Drive/email control family C": "familia C de control Drive/correo de treinta y ocho páginas localizada",
    "separately hashed 38-page annotated sibling": "hermano anotado de 38 páginas con hash separado",
    "located controlling seventy-seven-page family A": "familia A de control de setenta y siete páginas localizada",
    "located distinct seventy-seven-page family B": "familia B distinta de setenta y siete páginas localizada",
    "located twenty-four-page partial package in family C": "paquete parcial de veinticuatro páginas localizado en la familia C",
    "located forty-seven-page partial package in family C": "paquete parcial de cuarenta y siete páginas localizado en la familia C",
    "located fifty-page partial package in family C": "paquete parcial de cincuenta páginas localizado en la familia C",
    "separate two-page notice, not minutes": "convocatoria separada de dos páginas, no ACTA",
    "located two-page CEXP working export": "exportación de trabajo CEXP de dos páginas localizada",
    "actual two-page public-package control": "control real del paquete público de dos páginas",
    "located thirteen-page control copy with separate delivery communication": "copia de control de trece páginas localizada con comunicación de entrega separada",
    "located eight-page source A/control package source": "fuente A/de control del paquete de ocho páginas localizada",
    "located nine-page ACTAS.zip-derived public-package control": "control del paquete público de nueve páginas derivado de ACTAS.zip localizado",
    "located second nine-page binary": "segundo binario de nueve páginas localizado",
    "second partial eight-page sibling binary": "segundo binario hermano parcial de ocho páginas",
    "located exact nine-page control source": "fuente exacta de control de nueve páginas localizada",
    "located separate nine-page alternate binary": "binario alternativo separado de nueve páginas localizado",
    "separate one-page notice, not minutes": "convocatoria separada de una página, no ACTA",
    "located seven-page package control copy": "copia de control del paquete de siete páginas localizada",
    "separate seven-page binary variant recorded in section 4": "variante binaria separada de siete páginas registrada en la sección 4",
    "separately hashed seven-page highlighted sibling binary": "binario hermano resaltado de siete páginas con hash separado",
    "second separately hashed five-page capture": "segunda captura de cinco páginas con hash separado",
    "third separately hashed five-page capture": "tercera captura de cinco páginas con hash separado",
    "located six-page notarial response source": "fuente de respuesta notarial de seis páginas localizada",
    "located": "localizado",
    "preserved": "preservado",
    "referenced": "referido",
    "correspondence": "correspondencia",
    "communication": "comunicación",
    "source": "fuente",
    "sources": "fuentes",
    "family": "familia",
    "copy": "copia",
    "variant": "variante",
    "binary": "binario",
    "record": "registro",
    "records": "registros",
    "notice": "convocatoria",
    "agenda": "orden del día",
    "meeting": "reunión",
    "minutes": "ACTA",
    "official book": "libro oficial",
    "official-book": "libro oficial",
    "annexes": "anexos",
    "attachments": "adjuntos",
    "attachment": "adjunto",
    "proxies": "poderes",
    "proxy": "poder",
    "recipient": "destinatario",
    "recipients": "destinatarios",
    "service": "notificación",
    "delivery": "entrega",
    "receipt": "recepción",
    "authority": "autoridad",
    "capacities": "capacidades",
    "capacity": "capacidad",
    "authenticity": "autenticidad",
    "provenance": "procedencia",
    "integrity": "integridad",
    "comparison": "comparación",
    "relation": "relación",
    "relationship": "relación",
    "implementation": "ejecución",
    "execution": "formalización/ejecución",
    "accession": "adhesión",
    "schedule": "anexo",
    "schedules": "anexos",
    "amendment": "modificación",
    "amendments": "modificaciones",
    "issue": "incidencia",
    "issues": "cuestiones",
    "filename": "nombre de archivo",
    "date": "fecha",
    "body": "cuerpo",
    "authentication": "autenticación",
    "message": "mensaje",
    "locator": "localizador",
    "July": "julio",
    "proposal": "propuesta",
    "appointment": "nombramiento",
    "language": "texto",
    "recital": "mención",
    "recitals": "menciones",
    "connected": "conectadas",
    "file": "archivo",
    "files": "archivos",
    "contract": "contrato",
    "contracts": "contratos",
    "executed": "formalizado",
    "personnel": "personal",
    "payroll": "nóminas",
    "invoices": "facturas",
    "logs": "registros operativos",
    "bank": "banco",
    "access": "acceso",
    "actor-specific": "específica de cada actor",
    "performance": "ejecución",
    "claims": "pretensiones",
    "consignation": "consignación",
    "judgments": "sentencias",
    "appeals": "apelaciones",
    "holdings": "pronunciamientos",
    "admitted": "admitida",
    "competent": "competente",
    "scope": "alcance",
    "reversal": "revocación",
    "termination": "terminación",
    "indivisibility": "indivisibilidad",
    "restitution": "restitución",
    "headers": "cabeceras",
    "engagement": "encargo",
    "privilege": "privilegio",
    "review": "revisión",
    "event": "evento",
    "official act": "acto oficial",
    "sender": "remitente",
    "privacy": "privacidad",
    "status": "estado",
    "existence": "existencia",
    "metadata": "metadatos",
    "publicly": "públicamente",
    "reviewed": "revisados",
    "first-instance": "primera instancia",
    "certified": "certificado",
    "package": "paquete",
    "packages": "paquetes",
    "new-evidence": "de prueba nueva",
    "precise": "preciso",
    "reliance": "uso",
    "procedural": "procesal",
    "export": "exportación",
    "revisions": "revisiones",
    "revision": "revisión",
    "participants": "participantes",
    "participant": "participante",
    "signatures": "firmas",
    "signature": "firma",
    "acts": "actos",
    "reply": "respuesta",
    "safe": "apto",
    "editions": "ediciones",
    "custody": "custodia",
    "email": "correo",
    "request": "solicitud",
    "chain": "cadena",
    "copies": "copias",
    "forwarded": "reenviadas",
    "direct": "directo",
    "line": "línea",
    "account": "cuenta",
    "accounts": "cuentas",
    "reconciliation": "conciliación",
    "relationships": "relaciones",
    "formulas": "fórmulas",
    "formula": "fórmula",
    "support": "soporte",
    "extraction": "extracción",
    "controlled": "controlada",
    "version": "versión",
    "used": "utilizada",
    "thread": "hilo",
    "confirmed": "confirmada",
    "attendees": "asistentes",
    "attendance": "asistencia",
    "notes": "notas",
    "agreement": "acuerdo",
    "follow-up": "seguimiento",
    "ledgers": "libros contables",
    "report": "informe",
    "presented": "presentado",
    "final": "final",
    "adoption": "adopción",
    "identity": "identidad",
    "downstream": "posterior",
    "use": "uso",
    "supports": "sustenta",
    "establishes": "acredita",
    "delivered": "entregado",
    "earlier": "anteriormente",
    "effective-operation": "explotación efectiva",
    "evidence": "prueba",
    "acknowledgement": "acuse de recibo",
    "morosity-vote": "morosidad-voto",
    "vote": "voto",
    "votes": "votos",
    "voting": "votación",
    "arithmetic": "aritmética",
    "debt": "deuda",
    "security": "seguridad",
    "locksmith": "cerrajería",
    "instructions": "instrucciones",
    "key": "llave",
    "lock": "cerradura",
    "unit": "unidad",
    "units": "unidades",
    "reach": "alcance",
    "affected": "afectadas",
    "title": "título",
    "possession": "posesión",
    "basis": "base",
    "proceedings": "procedimientos",
    "link": "enlace",
    "links": "enlaces",
    "exist": "existen",
    "apply": "se aplican",
    "intake": "entrada",
    "tax": "tributario",
    "secrecy": "secreto",
    "conflicts": "conflictos",
    "payments": "pagos",
    "mixed": "mixtas",
    "three": "tres",
    "four": "cuatro",
    "five": "cinco",
    "six": "seis",
    "seven": "siete",
    "eight": "ocho",
    "nine": "nueve",
    "page": "página",
    "pages": "páginas",
    "count": "recuento",
    "equivalence": "equivalencia",
    "fields": "campos",
    "provider": "proveedor",
    "annotations": "anotaciones",
    "conversion": "conversión",
    "master": "maestro",
    "alternate": "alternativo",
    "mapping": "mapeo",
    "same-size": "del mismo tamaño",
    "size": "tamaño",
    "conflict": "conflicto",
    "differs": "difiere",
    "registered": "registrada",
    "difference": "diferencia",
    "issuer": "emisor",
    "inclusion": "inclusión",
    "omitted-page": "página omitida",
    "second": "segunda",
    "occurrence": "aparición",
    "content": "contenido",
    "provider-copy": "copia del proveedor",
    "actual": "real",
    "revision/signature": "revisión/firma",
    "revisions/signatures": "revisiones/firmas",
    "binaries": "binarios",
    "two": "dos",
    "formulas/source": "fórmulas/fuente",
    "statement": "declaración",
    "circulation": "circulación",
    "response": "respuesta",
    "challenge": "impugnación",
    "challenges": "impugnaciones",
    "budget": "presupuesto",
    "proof": "prueba",
    "text": "texto",
    "signed": "firmado",
    "adoption": "adopción",
    "not": "no",
    "by": "por",
    "litigation": "litigio",
    "judicial": "judicial",
    "court": "órgano judicial",
    "filing": "presentación",
    "appeal": "apelación",
    "judgment": "sentencia",
    "order": "orden",
    "audio": "audio",
    "manual": "manual",
    "verification": "verificación",
    "verified": "verificado",
    "complete": "completo",
    "incomplete": "incompleto",
    "missing": "ausente",
    "unlocated": "no localizado",
    "not located": "no localizado",
    "unresolved": "no resuelto",
    "remain open": "siguen abiertos",
    "remains open": "sigue abierto",
    "open": "abierto",
    "exact": "exacto",
    "original": "original",
    "native": "nativo",
    "public": "público",
    "private": "privado",
    "separate": "separado",
    "distinct": "distinto",
    "later": "posterior",
    "prior": "anterior",
    "primary": "primario",
    "partial": "parcial",
    "full": "completo",
    "all": "todos",
    "each": "cada",
    "and": "y",
    "or": "o",
    "with": "con",
    "without": "sin",
    "from": "desde",
    "within": "dentro de",
    "across": "entre",
    "against": "contra",
    "to": "a",
    "of": "de",
    "in": "en",
    "the": "el",
}


EXACT_ES: dict[str, str] = {
    # Document type.
    "source-copy-of-acta": "Copia fuente de ACTA",
    "acta": "ACTA",
    "private-native-AMR-audio-source": "Fuente de audio AMR nativa privada",
    "negative-search-record": "Registro de búsqueda negativa",
    "procedural-extract-related-to-acta": "Extracto procesal relacionado con ACTA",
    "meeting-notice": "Convocatoria de reunión",
    "exploitation-cession-and-statutes": "Cesión de explotación y estatutos",
    "acta-or-cost-arrangement-record": "ACTA o registro de acuerdo de costes",
    "meeting-notice-and-agenda": "Convocatoria y orden del día",
    "written-work-proposal": "Propuesta de trabajo escrita",
    "civil-challenge-and-litigation-records": "Registros de impugnación civil y litigios",
    "signed-stamped-notice": "Convocatoria firmada y sellada",
    "contract": "Contrato",
    "email-transmission-of-historic-actas": "Transmisión por correo de ACTAS históricas",
    "statement-and-circulation": "Declaración y circulación",
    "judicial-proceeding-records": "Registros de procedimiento judicial",
    "email": "Correo electrónico",
    "ordinary-meeting-and-notarial-presence-record": "Junta ordinaria y ACTA notarial de presencia",
    "notarial-response-or-challenge": "Respuesta o impugnación notarial",
    "debt-summary-convocation-and-president-letter": "Resumen de deuda, convocatoria y carta de la presidenta",
    "email-transmission-of-legal-and-acta-material": "Transmisión por correo de material jurídico y ACTAS",
    "convocation-notice-agenda-and-analysis-package": "Paquete de convocatoria, orden del día y análisis",
    "record-request-and-debt-challenge": "Solicitud de registros e impugnación de deuda",
    "authority-or-refusal-communication": "Comunicación de autoridad o negativa",
    "acta-and-annex-corpus": "Corpus de ACTA y anexos",
    "post-ACTA-expenditure-and-debt-analysis": "Análisis posterior al ACTA de gastos y deuda",
    "recorded-professional-working-meeting": "Reunión profesional de trabajo grabada",
    "meeting-scheduling-correspondence": "Correspondencia de programación de reunión",
    "signed-professional-accounting-report": "Informe contable profesional firmado",
    "native-professional-accounting-report-v3": "Informe contable profesional nativo v3",
    "same-day-carrier-email-with-report": "Correo portador del mismo día con informe",
    "professional-follow-up-email": "Correo profesional de seguimiento",
    "email-chain-recital-of-prior-delivery": "Cadena de correo que refiere entrega anterior",
    "audio-transcript-derivatives": "Derivados de transcripción de audio",
    "agreements-and-acta-circulation-communications": "Comunicaciones sobre acuerdos y circulación del ACTA",
    "email-circulation-of-historic-actas": "Circulación por correo de ACTAS históricas",
    "later-recited-meeting-or-event": "Reunión o evento referido posteriormente",
    "security-access-implementation-and-proceeding-records": "Registros de ejecución y procedimientos sobre seguridad/acceso",
    "judicial-auto": "Auto judicial",
    "tax-inspection-selection-and-commencement-records": "Registros de selección e inicio de inspección tributaria",
    "email-transmission-of-actas-and-related-material": "Transmisión por correo de ACTAS y material relacionado",
    "civil-challenge-reliance-record": "Registro de uso en impugnación civil",
    "judicial-reliance-record": "Registro de uso judicial",
    "judicial-interim-measure-reliance-record": "Registro de uso judicial en medida cautelar",
    "judgment-reliance-record": "Registro de uso en sentencia",
    "insolvency-debt-reliance-record": "Registro de uso concursal de deuda",
    "security-access-reliance-and-implementation-record": "Registro de uso y ejecución sobre seguridad/acceso",
    "provisional-criminal-archive-reliance-record": "Registro de uso en archivo penal provisional",
    "project-licence-finance-reliance-record": "Registro de uso sobre proyecto/licencia/financiación",
    "tax-reliance-record": "Registro de uso tributario",
    "exploitation-cession-and-cexp-statutes": "Cesión de explotación y estatutos CEXP",
    "signed-stamped-cexp-notice": "Convocatoria CEXP firmada y sellada",
    "five-page-president-statement": "Declaración de la presidencia de cinco páginas",
    "referenced-written-objection-unlocated": "Objeción escrita referida y no localizada",
    "proxy-or-representation-instrument": "Instrumento de poder o representación",
    "155-page-ordinary-meeting-notarial-record": "ACTA notarial de junta ordinaria de 155 páginas",
    "later-recital-of-unlocated-event": "Mención posterior de evento no localizado",
    "universal-extraordinary-CEXP-meeting-record": "ACTA de reunión universal extraordinaria CEXP",
    "six-page-image-only-source-with-sworn-english-translation": "Fuente de seis páginas sólo imagen con traducción jurada inglesa",
    "partial-six-page-typed-version-three-PNG-pages-located": "Versión mecanografiada parcial de seis páginas; tres PNG localizados",
    "six-page-notarial-response-source": "Fuente de respuesta notarial de seis páginas",

    # Issuer / sender.
    "Owners' Community": "Comunidad de Propietarios",
    "Owners' Community extraordinary meeting": "Junta extraordinaria de la Comunidad de Propietarios",
    "Owners' Community ordinary meeting": "Junta ordinaria de la Comunidad de Propietarios",
    "CEXP General Meeting": "Junta General de CEXP",
    "Owners' Community / participating-owner CEXP formation meeting": "Comunidad de Propietarios / reunión de propietarios participantes para constituir CEXP",
    "Owners' Community / participating owners": "Comunidad de Propietarios / propietarios participantes",
    "CEXP/project counterparties identified in the instruments": "Contrapartes de CEXP/del proyecto identificadas en los instrumentos",
    "recorded Community/project participants": "Participantes de la Comunidad/del proyecto consignados",
    "Owners' Community/cost and exploitation record, exact characterization open": "Comunidad de Propietarios / registro de costes y explotación; caracterización exacta abierta",
    "Owners' Community chair, as referenced": "Presidencia de la Comunidad de Propietarios, según la referencia",
    "repository/source review": "Revisión del repositorio/de las fuentes",
    "challenging parties and competent court(s); exact complete file not located": "Partes impugnantes y órgano(s) judicial(es) competente(s); expediente completo exacto no localizado",
    "LPB and Monterecco counterparties": "Contrapartes LPB y Monterecco",
    "project-side sender; identity withheld in this public ledger": "Remitente del lado del proyecto; identidad reservada en este registro público",
    "LPB/Gil-side author/sender; exact author and sender chain unresolved": "Autor/remitente del lado LPB/Gil; autoría y cadena exacta de remisión no resueltas",
    "competent first-instance and appeal court(s)": "Órgano(s) judicial(es) competente(s) de primera instancia y apelación",
    "Pamanil-related sender; identity withheld/unresolved": "Remitente relacionado con Pamanil; identidad reservada/no resuelta",
    "Community chair/administrator workstream": "Línea de trabajo de presidencia/administración de la Comunidad",
    "project-side sender; identity withheld": "Remitente del lado del proyecto; identidad reservada",
    "Community notice issuer(s) and forwarding parties; exact sender chain source-specific": "Emisor(es) del aviso comunitario y partes que lo reenviaron; cadena exacta de remisión dependiente de cada fuente",
    "project/LPB-side requester": "Solicitante del lado del proyecto/LPB",
    "correspondents in AC/PwC/LPB workstream; original sender unresolved": "Corresponsales de la línea AC/PwC/LPB; remitente original no resuelto",
    "Jonathan Simó and project/PwC workstream contributors": "Jonathan Simó y colaboradores de la línea de trabajo proyecto/PwC",
    "PwC/adviser workstream": "Línea de trabajo PwC/asesores",
    "project/adviser correspondents; identities withheld": "Corresponsales del proyecto/asesores; identidades reservadas",
    "Jonathan Simó Morales / professional consultancy heading": "Jonathan Simó Morales / encabezamiento de consultoría profesional",
    "project-side sender; identity minimized in public ledger": "Remitente del lado del proyecto; identidad minimizada en el registro público",
    "PwC/adviser workstream correspondent(s); identities minimized": "Corresponsal(es) de la línea PwC/asesores; identidades minimizadas",
    "transcription service/workstream": "Servicio/línea de trabajo de transcripción",
    "Pamalexsha/Pamanil/Community correspondents; exact senders source-specific": "Corresponsales Pamalexsha/Pamanil/Comunidad; remitentes exactos dependientes de cada fuente",
    "private sender; identity minimized in public ledger": "Remitente privado; identidad minimizada en el registro público",
    "not located": "No localizado",
    "Community/security/LPB/insolvency actors as separately alleged or documented; exact issuer per act unresolved": "Actores de Comunidad/seguridad/LPB/insolvencia según se alegan o documentan por separado; emisor exacto de cada acto no resuelto",
    "competent court; exact certified source control incomplete": "Órgano judicial competente; control exacto de fuente certificada incompleto",
    "private correspondents; identities minimized in public ledger": "Corresponsales privados; identidades minimizadas en el registro público",
    "challenging parties and competent court(s)": "Partes impugnantes y órgano(s) judicial(es) competente(s)",
    "JV 1260/AP 89/2014 judicial bodies": "Órganos judiciales de JV 1260/AP 89/2014",
    "PO 562/2014 court": "Órgano judicial de PO 562/2014",
    "court issuing Sentencia 268/2015": "Órgano judicial que dictó la Sentencia 268/2015",
    "Community creditors/officeholders, insolvency participants and court actors as separately documented": "Acreedores/cargos comunitarios, participantes concursales y actores judiciales según se documentan por separado",
    "Community/security/LPB/insolvency actors as separately documented": "Actores de Comunidad/seguridad/LPB/insolvencia según se documentan por separado",
    "court issuing Auto 804/2018": "Órgano judicial que dictó el Auto 804/2018",
    "project/licence/unitary-operation/levy actors as separately documented": "Actores del proyecto/licencia/explotación unitaria/derrama según se documentan por separado",
    "AEAT and procedural participants": "AEAT y participantes procesales",
    "CEXP and instrument counterparties": "CEXP y contrapartes del instrumento",
    "grantor protected in source custody": "Poderdante protegido en la custodia de la fuente",
    "4 February 2022 Owners' Community ACTA as carrier": "ACTA de la Comunidad de Propietarios de 4 de febrero de 2022 como portadora",
    "procedural-document carrier; exact author/issuer remains source-specific": "Portador de documento procesal; autor/emisor exacto dependiente de la fuente",
    "purported issuing/convoking body shown by the notice; exact issuer and authority remain source-specific": "Pretendido órgano emisor/convocante mostrado por el aviso; emisor y autoridad exactos dependientes de la fuente",

    # Stated capacity.
    "meeting body or recorded event; individual capacities remain source-specific": "Órgano de reunión o evento registrado; las capacidades individuales dependen de cada fuente",
    "chair and administrator roles recorded": "Funciones de presidencia y administración consignadas",
    "economist/accounting professional; report based on supplied records, not an independent audit": "Economista/profesional contable; informe basado en registros aportados, no auditoría independiente",
    "finite-search recorder; not a historical meeting issuer": "Responsable de una búsqueda finita; no emisor histórico de la reunión",
    "recorded meeting body; individual signatories protected": "Órgano de reunión consignado; firmantes individuales protegidos",
    "contracting parties; exact execution/adhesion capacities require schedules": "Partes contratantes; las capacidades exactas de firma/adhesión requieren los anexos",
    "meeting body; acting officers recorded": "Órgano de reunión; cargos accidentales consignados",
    "LPB representation and CEXP connection recorded; exact capacities source-sensitive": "Representación de LPB y conexión con CEXP consignadas; capacidades exactas dependientes de la fuente",
    "meeting body; officers partly protected": "Órgano de reunión; cargos parcialmente protegidos",
    "meeting body; LPB chair representation recorded": "Órgano de reunión; representación de LPB en la presidencia consignada",
    "meeting body; new officeholders elected during meeting": "Órgano de reunión; nuevos cargos elegidos durante la reunión",
    "chair/meeting convener as recorded in later minutes": "Presidencia/convocante según consta en ACTAS posteriores",
    "meeting body; chair and administrator roles recorded": "Órgano de reunión; funciones de presidencia y administración consignadas",
    "proposed service provider; exact legal-person/capacity source-controlled separately": "Proveedor de servicios propuesto; persona jurídica/capacidad exacta controlada por separado en la fuente",
    "litigants/court in episode-specific capacities": "Litigantes/órgano judicial en capacidades específicas del episodio",
    "purported operating-body issuer; competent authority still to be proved": "Pretendido emisor del órgano de explotación; autoridad competente aún por probar",
    "contracting legal persons; each signatory capacity requires the executed original": "Personas jurídicas contratantes; la capacidad de cada firmante requiere el original formalizado",
    "sender in project/legal-advice workstream; exact engagement capacity private": "Remitente en la línea de proyecto/asesoría jurídica; capacidad exacta del encargo privada",
    "party-side account; no Community mandate inferred": "Relato de parte; no se infiere mandato de la Comunidad",
    "judicial bodies in period-specific possession/operation dispute": "Órganos judiciales en controversia de posesión/explotación específica del periodo",
    "capacity not established by public metadata": "Capacidad no establecida por los metadatos públicos",
    "LPB chair represented by its director": "Presidencia de LPB representada por su administrador",
    "CEXP General Meeting body; individual capacities/signatures require native review": "Órgano Junta General de CEXP; capacidades/firmas individuales requieren revisión del nativo",
    "purported Community notice issuers; exact message senders/capacities source-specific": "Pretendidos emisores de la convocatoria comunitaria; remitentes/capacidades exactos dependientes de cada fuente",
    "party-side source-transmission role; no independent adoption inferred": "Función de transmisión de fuente de parte; no se infiere adopción independiente",
    "Community officer/forwarder capacities not completely reconciled": "Capacidades de cargo comunitario/reenviador no conciliadas por completo",
    "party-side requester; exact signatory capacity requires source review": "Solicitante de parte; la capacidad exacta del firmante requiere revisión de la fuente",
    "reported procedural/advisory capacities; no broader mandate inferred": "Capacidades procesales/de asesoría referidas; no se infiere mandato más amplio",
    "professional/accounting and party-side analytical capacities; not an independent audit or adjudication": "Capacidades profesionales/contables y analíticas de parte; no auditoría independiente ni decisión judicial",
    "professional meeting arrangers/participants; exact capacities incomplete": "Organizadores/participantes de reunión profesional; capacidades exactas incompletas",
    "persons arranging potential AC engagement; no confirmed mandate or meeting inferred": "Personas que organizan un posible encargo de la AC; no se infiere mandato ni reunión confirmados",
    "party-side sender circulating professional report and legal/debt challenge": "Remitente de parte que circula informe profesional e impugnación jurídica/de deuda",
    "professional follow-up; no Community or court mandate inferred": "Seguimiento profesional; no se infiere mandato de la Comunidad ni judicial",
    "professional author recalling prior delivery": "Autor profesional que recuerda una entrega anterior",
    "later transcript derivative producer; not an authenticator or certifier": "Productor posterior de un derivado de transcripción; no autentificador ni certificador",
    "CEXP General Meeting body; individual capacities protected/incomplete": "Órgano Junta General de CEXP; capacidades individuales protegidas/incompletas",
    "asserted officeholder/administrator/professional capacities; exact mandates unresolved": "Capacidades alegadas de cargo/administración/profesional; mandatos exactos no resueltos",
    "Community office/administrator continuity and elections recorded": "Continuidad y elecciones de cargos/administración comunitarios consignadas",
    "Community/Pamanil-lane officeholders; CAM/security context recorded": "Cargos del carril Comunidad/Pamanil; contexto CAM/seguridad consignado",
    "Community/CAM functions recorded; exact legal authority open": "Funciones Comunidad/CAM consignadas; autoridad jurídica exacta abierta",
    "document forwarder; no truth/adoption inferred": "Reenviador del documento; no se infiere verdad ni adopción",
    "capacities must be proved act by act; no common mandate inferred": "Las capacidades deben probarse acto por acto; no se infiere mandato común",
    "judicial body concerning a 28 November 2018 transaction": "Órgano judicial relativo a una operación de 28 de noviembre de 2018",
    "tax authority; each act's author/signatory and statutory capacity source-specific": "Autoridad tributaria; autor/firmante y capacidad legal de cada acto dependientes de la fuente",
    "Community record; CAM-supplied project and José Daniel Acosta Matos interventions recorded": "Registro comunitario; proyecto aportado por CAM e intervenciones de José Daniel Acosta Matos consignados",
    "document senders/forwarders; no truth, adoption or pre-meeting knowledge inferred": "Remitentes/reenviadores de documentos; no se infiere verdad, adopción ni conocimiento previo a la reunión",
    "litigants/judicial bodies; exact capacities and holdings incomplete": "Litigantes/órganos judiciales; capacidades y pronunciamientos exactos incompletos",
    "judicial bodies in period-specific dispute": "Órganos judiciales en controversia específica del periodo",
    "judicial body; exact current/final status incomplete": "Órgano judicial; estado actual/firme exacto incompleto",
    "judicial body in contract/operation dispute": "Órgano judicial en controversia contractual/de explotación",
    "each filing/certificate/review capacity must be proved separately": "La capacidad de cada escrito/certificado/revisión debe probarse por separado",
    "each request, instruction and act requires separate capacity proof": "Cada solicitud, instrucción y acto requiere prueba separada de capacidad",
    "judicial body in provisional criminal-archive context": "Órgano judicial en contexto de archivo penal provisional",
    "each public/private actor's capacity and authority must be proved separately": "La capacidad y autoridad de cada actor público/privado debe probarse por separado",
    "tax authority/taxpayer/procedural capacities; tax secrecy applies": "Capacidades de autoridad tributaria/contribuyente/procesales; se aplica el secreto tributario",
    "instrument parties; exact signatory/accession capacities require complete schedules": "Partes del instrumento; capacidades exactas de firma/adhesión requieren anexos completos",
    "purported notice issuer; competent authority open": "Pretendido emisor de convocatoria; autoridad competente abierta",
    "proxy grantor; scope source-specific": "Poderdante; alcance dependiente de la fuente",
    "later recital carrier, not 2018 convener/issuer": "Portador de mención posterior, no convocante/emisor de 2018",
    "four-page procedural extract; not minutes and not an ACTA variant": "Extracto procesal de cuatro páginas; no son ACTAS ni variante del ACTA",
    "separate notice for the 26-Apr-2016 meeting; not minutes": "Convocatoria separada para la reunión de 26-Apr-2016; no son ACTAS",
    "separate notice for the 5-Jul-2018 meeting; not minutes": "Convocatoria separada para la reunión de 5-Jul-2018; no son ACTAS",

    # Recipients.
    "historical recipients/participants as separately recorded; complete original recipient/service denominator unresolved": "Destinatarios/participantes históricos según se consignan por separado; denominador completo original de destinatarios/notificación no resuelto",
    "procedural parties": "Partes procesales",
    "owners/participants; complete list not located": "Propietarios/participantes; lista completa no localizada",
    "CEXP participants; complete accession/attendance list not located": "Participantes CEXP; lista completa de adhesión/asistencia no localizada",
    "owners/participants; complete entitlement denominator unresolved": "Propietarios/participantes; denominador completo de legitimación no resuelto",
    "owners/participants; complete entitlement/conflict denominator unresolved": "Propietarios/participantes; denominador completo de legitimación/conflicto no resuelto",
    "public register readers": "Lectores del registro público",
    "owners/participants; complete list protected or incomplete": "Propietarios/participantes; lista completa protegida o incompleta",
    "instrument counterparties and participants; complete accession list not located": "Contrapartes y participantes del instrumento; lista completa de adhesión no localizada",
    "participants; complete list not located": "Participantes; lista completa no localizada",
    "owners/participants; complete service and attendance lists not located": "Propietarios/participantes; listas completas de notificación y asistencia no localizadas",
    "owners/participants; complete service and attendance list not located": "Propietarios/participantes; lista completa de notificación y asistencia no localizada",
    "owners/eligible recipients; complete list not located": "Propietarios/destinatarios legitimados; lista completa no localizada",
    "owners/participants; complete attendance and entitlement denominator unresolved": "Propietarios/participantes; denominador completo de asistencia y legitimación no resuelto",
    "Owners' Community/meeting participants": "Comunidad de Propietarios/participantes en la reunión",
    "parties and court; complete service list not located": "Partes y órgano judicial; lista completa de notificación no localizada",
    "Monterecco/Pink-side recipient identified in the notice; complete service chain open": "Destinatario del lado Monterecco/Pink identificado en el aviso; cadena completa de notificación abierta",
    "contracting counterparties": "Contrapartes contratantes",
    "Garrigues legal advisers; exact individuals withheld": "Asesores jurídicos de Garrigues; personas exactas reservadas",
    "intended meeting/circulation recipients; exact list not located": "Destinatarios previstos de la reunión/circulación; lista exacta no localizada",
    "18 claimant units/parties; complete service denominator not located": "18 unidades/partes demandantes; denominador completo de notificación no localizado",
    "recipient(s) withheld/unresolved": "Destinatario(s) reservado(s)/no resuelto(s)",
    "owners/recipients; complete list and delivery proof not located": "Propietarios/destinatarios; lista completa y prueba de entrega no localizadas",
    "PwC advisers; exact recipients/capacities withheld or incomplete": "Asesores de PwC; destinatarios/capacidades exactos reservados o incompletos",
    "owners and forwarded recipients; complete service list not located": "Propietarios y destinatarios de reenvío; lista completa de notificación no localizada",
    "Community president and administrator": "Presidencia y administración de la Comunidad",
    "workstream recipients; complete original chain not located": "Destinatarios de la línea de trabajo; cadena original completa no localizada",
    "owners/participants; complete proxy/coefficient/vote denominator unresolved": "Propietarios/participantes; denominador completo de poderes/coeficientes/voto no resuelto",
    "project legal/advisory recipients; exact complete list withheld/incomplete": "Destinatarios jurídicos/de asesoría del proyecto; lista completa exacta reservada/incompleta",
    "PwC/adviser participants, Jonathan Simó, Cristo and Francisco Mario Matos Matas as recorded/referenced; authenticated list incomplete": "Participantes PwC/asesores, Jonathan Simó, Cristo y Francisco Mario Matos Matas según constan/se refieren; lista autenticada incompleta",
    "intended AC/adviser participants; complete list not located": "Participantes previstos AC/asesores; lista completa no localizada",
    "project/PwC workstream; exact original recipients incomplete": "Línea de trabajo proyecto/PwC; destinatarios originales exactos incompletos",
    "PwC/project review workstream; complete recipients incomplete": "Línea de revisión PwC/proyecto; destinatarios completos incompletos",
    "external legal/advisory counsel; exact private identity/capacity retained only in source custody": "Asesoría jurídica/consultiva externa; identidad/capacidad privada exacta conservada sólo en la custodia de la fuente",
    "project/adviser workstream and intended AC engagement; complete list incomplete": "Línea proyecto/asesores y encargo AC previsto; lista completa incompleta",
    "project/adviser recipients; exact complete list retained privately": "Destinatarios del proyecto/asesores; lista completa exacta conservada privadamente",
    "project/source-custody recipients; exact list not material to public record": "Destinatarios del proyecto/custodia de fuentes; lista exacta no material para el registro público",
    "private recipients; complete list and receipt proof not located": "Destinatarios privados; lista completa y prueba de recepción no localizadas",
    "private recipient(s); exact capacity incomplete": "Destinatario(s) privado(s); capacidad exacta incompleta",
    "affected owners/units, security providers and proceeding participants; complete denominator unresolved": "Propietarios/unidades afectados, proveedores de seguridad y participantes procesales; denominador completo no resuelto",
    "procedural parties; complete service record not located": "Partes procesales; registro completo de notificación no localizado",
    "taxpayer/procedural recipients; identities and tax data restricted": "Contribuyente/destinatarios procesales; identidades y datos tributarios restringidos",
    "owners/participants; complete service, proxy and entitlement denominator unresolved": "Propietarios/participantes; denominador completo de notificación, poderes y legitimación no resuelto",
    "private recipients; exact capacities incomplete": "Destinatarios privados; capacidades exactas incompletas",
    "18 claimant units/parties": "18 unidades/partes demandantes",
    "insolvency administration, court and procedural parties": "Administración concursal, órgano judicial y partes procesales",
    "affected parties, providers and proceeding participants": "Partes afectadas, proveedores y participantes procesales",
    "Yaiza, Cabildo, tourism authorities, financiers/investors and other recipients if evidenced; complete list open": "Yaiza, Cabildo, autoridades turísticas, financiadores/inversores y otros destinatarios si se acreditan; lista completa abierta",
    "taxpayer, representatives and reviewing bodies; details restricted": "Contribuyente, representantes y órganos revisores; detalles restringidos",
    "instrument counterparties/participants; complete list not located": "Contrapartes/participantes del instrumento; lista completa no localizada",
    "Monterecco-side recipient; complete service chain private/incomplete": "Destinatario del lado Monterecco; cadena completa de notificación privada/incompleta",
    "proxy holder/meeting body; identities minimized": "Apoderado/órgano de reunión; identidades minimizadas",
    "2022 ACTA recipients; original recipients unlocated": "Destinatarios del ACTA de 2022; destinatarios originales no localizados",
    "procedural recipients/service denominator unresolved": "Destinatarios procesales/denominador de notificación no resuelto",
    "intended notice recipients and complete service denominator unresolved": "Destinatarios previstos de la convocatoria y denominador completo de notificación no resueltos",

    # Meeting body.
    "not a meeting body": "No es un órgano de reunión",
    "professional workstream": "Línea de trabajo profesional",
    "Owners' Community context": "Contexto de la Comunidad de Propietarios",
    "participating-owner CEXP formation meeting": "Reunión de propietarios participantes para constituir CEXP",
    "CEXP, not the Owners' Community": "CEXP, no la Comunidad de Propietarios",
    "Owners' Community/cost-exploitation event, exact characterization open": "Comunidad de Propietarios/evento de costes-explotación; caracterización exacta abierta",
    "CEXP-related, not the Owners' Community": "Relacionado con CEXP, no con la Comunidad de Propietarios",
    "competing Community governance context": "Contexto de gobernanza comunitaria competidora",
    "Owners' Community convocation context": "Contexto de convocatoria de la Comunidad de Propietarios",
    "professional workstream; linked to 26 April ACTA, not an organ meeting": "Línea de trabajo profesional; vinculada al ACTA de 26 de abril, no reunión de órgano",
    "professional working meeting; not Owners' Community/CEXP": "Reunión profesional de trabajo; no Comunidad de Propietarios/CEXP",
    "proposed professional/AC engagement, not a proved meeting": "Encargo profesional/AC propuesto; no reunión acreditada",
    "Community delivery context, not itself a meeting record": "Contexto de entrega comunitaria; no es por sí mismo registro de reunión",
    "legal body unresolved": "Órgano jurídico no resuelto",
    "CEXP, not Owners' Community": "CEXP, no Comunidad de Propietarios",
    "CEXP context": "Contexto CEXP",
    "Owners' Community in a contested governance setting": "Comunidad de Propietarios en un contexto de gobernanza controvertido",
    "original body unresolved": "Órgano original no resuelto",
    "not a meeting body; related to the 19-Nov-2015 ACTA family": "No es un órgano de reunión; relacionado con la familia ACTA de 19-Nov-2015",

    # Documented convener.
    "not applicable": "No aplicable",
    "Asunción Aizpurúa Sánchez as chair and Francisco Matos Matas as administrator are recorded.": "Constan Asunción Aizpurúa Sánchez como presidenta y Francisco Matos Matas como administrador.",
    "The copy records notice by registered mail; the individual convener is unresolved.": "La copia consigna convocatoria por correo certificado; la persona convocante no está resuelta.",
    "Chair's notice and Francisco Mario Matos Matas acting as administrator are recorded.": "Constan convocatoria por la presidenta y Francisco Mario Matos Matas actuando como administrador.",
    "Community/Pamanil-lane officeholders recorded; CAM presence and security proposal context appear in the minutes.": "Constan cargos del carril Comunidad/Pamanil; la presencia de CAM y el contexto de la propuesta de seguridad figuran en el ACTA.",
    "Original convener unresolved; new officeholders were elected during the meeting.": "Convocante original no resuelto; durante la reunión se eligieron nuevos cargos.",
    "CEXP meeting recorded; individual notice authority and signed/native relation remain open.": "Reunión CEXP consignada; autoridad individual para convocar y relación firma/nativo siguen abiertas.",
    "Community/CAM functions are recorded; exact legal-convener authority remains source-dependent.": "Constan funciones Comunidad/CAM; la autoridad jurídica exacta del convocante depende de la fuente.",
    "Community-organ action and CAM/José Daniel Acosta Matos interventions are recorded; complete legal-convener proof open.": "Constan actuación del órgano comunitario e intervenciones de CAM/José Daniel Acosta Matos; prueba completa de la autoridad jurídica del convocante abierta.",
    "individual convener not publicly closed": "Persona convocante no cerrada públicamente",
    "Asunción Aizpurúa Sánchez chair; Francisco Matos Matas administrator": "Asunción Aizpurúa Sánchez, presidenta; Francisco Matos Matas, administrador",
    "exact legal-convener authority open": "Autoridad jurídica exacta del convocante abierta",
    "Acting chair and secretary-administrator recorded; exact convener unresolved.": "Constan presidencia accidental y secretario-administrador; convocante exacto no resuelto.",
    "Formal convener unresolved; LPB representation also linked to CEXP is recorded.": "Convocante formal no resuelto; también consta representación de LPB vinculada a CEXP.",
    "CEXP meeting recorded; individual notice authority and native signature relation remain open.": "Reunión CEXP consignada; autoridad individual para convocar y relación con firma nativa siguen abiertas.",
    "individual convener unresolved": "Persona convocante no resuelta",
    "not a meeting notice/convener record": "No es registro de convocatoria/convocante de reunión",
    "acting chair/secretary recorded; exact convener unresolved": "Constan presidencia/secretaría accidentales; convocante exacto no resuelto",
    "formal convener unresolved": "Convocante formal no resuelto",
    "chair and acting secretary recorded; source notice unjoined": "Constan presidenta y secretaria accidental; convocatoria fuente no incorporada",
    "chair acting for LPB recorded": "Consta presidencia actuando por LPB",
    "original convener unresolved": "Convocante original no resuelto",
    "chair's notice referenced": "Se refiere convocatoria de la presidenta",
    "chair's notice; Francisco Mario Matos Matas recorded as administrator": "Convocatoria de la presidenta; Francisco Mario Matos Matas consta como administrador",
    "LPB chair and 8 August notice recorded": "Constan presidencia de LPB y convocatoria de 8 de agosto",
    "chair/administrator lane reflected in the later minutes": "Carril presidencia/administración reflejado en ACTAS posteriores",
    "chair/administrator lane recorded in later minutes": "Carril presidencia/administración consignado en ACTAS posteriores",
    "PwC arrangement supported; exact initiator unresolved": "Organización por PwC respaldada; iniciador exacto no resuelto",
    "officeholder continuity recorded; complete source notice open": "Continuidad de cargos consignada; convocatoria fuente completa abierta",
    "complete legal-convener authority open": "Autoridad jurídica completa del convocante abierta",
    "Chair and acting secretary recorded; source notice not joined and perimeter unresolved.": "Constan presidencia y secretaría accidental; convocatoria fuente no incorporada y perímetro no resuelto.",
    "Minutes record the chair acting for LPB; complete notice/service remains open.": "El ACTA consigna a la presidencia actuando por LPB; convocatoria/notificación completa sigue abierta.",
    "Resumed chair functions and LPB/Gil signatures recorded; opponents challenged the notice.": "Constan reanudación de funciones de presidencia y firmas LPB/Gil; opositores impugnaron la convocatoria.",
    "LPB chair represented by its director; prior notice dated 8 August recorded.": "Presidencia de LPB representada por su administrador; consta convocatoria previa de 8 de agosto.",
    "Community officeholder continuity and elections are recorded; complete service remains open.": "Constan continuidad y elecciones de cargos comunitarios; notificación completa sigue abierta.",
    "not applicable to this distinct procedural extract": "No aplicable a este extracto procesal diferenciado",
    "convener/capacity as stated in the notice; legal authority and complete service remain open": "Convocante/capacidad según constan en la convocatoria; autoridad jurídica y notificación completa siguen abiertas",

    # Public/private status.
    "private native/public-safe metadata or redacted derivative": "Nativo privado/metadatos aptos para publicación o derivado redactado",
    "private native/control source; public irreversible redacted raster facsimile, source-page gallery, OCR text edition and text-edition PDF available through the linked event page": "Fuente nativa/de control privada; facsímil raster redactado irreversiblemente, galería de páginas fuente, edición textual OCR y PDF de edición textual públicos disponibles en la página enlazada del evento",
    "private preserved source/variant; public-safe metadata and relationship only unless included in the linked control-copy package": "Fuente/variante preservada privadamente; sólo metadatos y relación aptos para publicación salvo inclusión en el paquete enlazado de copia de control",
    "mixed public/private judicial records": "Registros judiciales públicos/privados mixtos",
    "mixed private/public judicial records": "Registros judiciales privados/públicos mixtos",

    # Exact open-issue translations (reader-facing Spanish cards).
    "material equivalence, provenance/authenticity and official-book relation remain open unless separately stated": "Salvo indicación separada, siguen abiertas la equivalencia material, la procedencia/autenticidad y la relación con el libro oficial",
    "inclusion/annex relationship and missing pages open": "Siguen abiertas la relación de inclusión/anexo y las páginas ausentes",
    "original books, officeholder files, all custodians and deleted/outside systems remain unsearched or incomplete; absence is not nonexistence": "Los libros originales, archivos de cargos, todos los custodios y sistemas eliminados o externos siguen sin buscarse o incompletos; la ausencia no equivale a inexistencia",
    "exact procedural classification, author/issuer, filing/service context and relationship to the ACTA remain unresolved": "Siguen sin resolverse la clasificación procesal exacta, el autor/emisor, el contexto de presentación/notificación y la relación con el ACTA",
    "issuer capacity, complete recipient/service proof, delivery, authority and notice-to-meeting relationship remain open": "Siguen abiertas la capacidad del emisor, la prueba completa de destinatarios/notificación, la entrega, la autoridad y la relación entre convocatoria y reunión",
    "authenticity, official-book relation and material comparison across all four binaries remain open": "Siguen abiertas la autenticidad, la relación con el libro oficial y la comparación material de los cuatro binarios",
    "notice, proxies, exact signed text, annexes and official-book comparison remain open": "Siguen abiertas la convocatoria, los poderes, el texto firmado exacto, los anexos y la comparación con el libro oficial",
    "complete execution, accession, finca scope and amendment schedule remain open": "Siguen abiertas la formalización completa, la adhesión, el alcance por finca y el cuadro de modificaciones",
    "six-page/nine-page relationship, notice, annexes, votes and implementation remain open": "Siguen abiertas la relación entre las versiones de seis y nueve páginas, la convocatoria, los anexos, los votos y la ejecución",
    "date/body authentication, complete message locator, notice, annexes and 15 July relationship remain open": "Siguen abiertas la autenticación de fecha/órgano, el localizador completo del mensaje, la convocatoria, los anexos y la relación con el 15 de julio",
    "notice, attendance, accounts, budget, annexes, votes and official-book comparison remain open": "Siguen abiertas la convocatoria, la asistencia, las cuentas, el presupuesto, los anexos, los votos y la comparación con el libro oficial",
    "notice, attendance, accounts, challenges, annexes and implementation remain open": "Siguen abiertas la convocatoria, la asistencia, las cuentas, las impugnaciones, los anexos y la ejecución",
    "notice, proxies, variant reconciliation, challenge record and official book remain open": "Siguen abiertas la convocatoria, los poderes, la conciliación de variantes, el registro de impugnación y el libro oficial",
    "original notice, agenda, recipients and delivery proof remain open": "Siguen abiertas la convocatoria original, el orden del día, los destinatarios y la prueba de entrega",
    "official book, audio, proxies, debt schedule, voting arithmetic and variant reconciliation remain open": "Siguen abiertos el libro oficial, el audio, los poderes, el cuadro de deuda, la aritmética de voto y la conciliación de variantes",
    "contract, personnel, payroll, invoices, logs, bank, access and actor-specific performance remain open": "Siguen abiertos el contrato, el personal, las nóminas, las facturas, los registros operativos, el banco, el acceso y la ejecución específica de cada actor",
    "complete claims, consignation, judgments, appeals, service, exact holdings and source admitted remain open": "Siguen abiertas las pretensiones completas, la consignación, las sentencias, las apelaciones, la notificación, los pronunciamientos exactos y la fuente admitida",
    "competent authority, full notice chain, finca scope and later reversal/termination remain open": "Siguen abiertas la autoridad competente, la cadena completa de convocatoria, el alcance por finca y la revocación/terminación posterior",
    "executed original, schedules, authority, indivisibility, restitution and complete litigation chain remain open": "Siguen abiertos el original formalizado, los anexos, la autoridad, la indivisibilidad, la restitución y la cadena litigiosa completa",
    "native headers, attachment hashes, engagement scope and privilege review remain open": "Siguen abiertas las cabeceras nativas, los hashes de adjuntos, el alcance del encargo y la revisión de privilegio",
    "exact event date, official act, sender, recipients, attachments, privacy and privilege status remain open": "Siguen abiertos la fecha exacta del evento, el acto oficial, el remitente, los destinatarios, los adjuntos, la privacidad y el estado de privilegio",
    "certified complete record, new-evidence package and precise source-by-source reliance remain open": "Siguen abiertos el registro completo certificado, el paquete de prueba nueva y el uso preciso fuente por fuente",
    "native body, headers, attachments, capacities and relationship to the meeting remain open": "Siguen abiertos el cuerpo nativo, las cabeceras, los adjuntos, las capacidades y la relación con la reunión",
    "full notice/service, votes, annexes, native/certified comparison and implementation remain open": "Siguen abiertas la convocatoria/notificación completa, los votos, los anexos, la comparación nativo/certificado y la ejecución",
    "native export/revisions, participants, authority, signatures and later acts remain open": "Siguen abiertas la exportación/revisiones nativas, los participantes, la autoridad, las firmas y los actos posteriores",
    "native headers, complete recipients/delivery, attachment hashes and public-safe editions remain open": "Siguen abiertas las cabeceras nativas, los destinatarios/entrega completos, los hashes de adjuntos y las ediciones aptas para publicación",
    "variant differences, annexes, audio, debt arithmetic, proxies, coefficients and implementation remain open": "Siguen abiertas las diferencias entre variantes, los anexos, el audio, la aritmética de deuda, los poderes, los coeficientes y la ejecución",
    "attachment hashes, exact recipients/capacities and privilege review remain open": "Siguen abiertos los hashes de adjuntos, los destinatarios/capacidades exactos y la revisión de privilegio",
    "service, attachments, hashes, photographed-page map, recipients and privilege/privacy review remain open": "Siguen abiertas la notificación, los adjuntos, los hashes, el mapa de páginas fotografiadas, los destinatarios y la revisión de privilegio/privacidad",
    "delivery, response and complete attachments remain open": "Siguen abiertas la entrega, la respuesta y los adjuntos completos",
    "native original, headers, complete body/attachments, capacities and privilege review remain open": "Siguen abiertos el original nativo, las cabeceras, el cuerpo/adjuntos completos, las capacidades y la revisión de privilegio",
    "manual source-line verification, official book/audio/proxies, source-account reconciliation and variant relationships remain open": "Siguen abiertas la verificación manual línea por línea, el libro oficial/audio/poderes, la conciliación fuente-cuentas y las relaciones entre variantes",
    "controlled extraction, formulas, invoices/accounts, exact version used and privilege review remain open": "Siguen abiertas la extracción controlada, las fórmulas, las facturas/cuentas, la versión exacta utilizada y la revisión de privilegio",
    "full thread, confirmed meeting, attendees, notes, agreement and follow-up remain open": "Siguen abiertos el hilo completo, la reunión confirmada, los asistentes, las notas, el acuerdo y el seguimiento",
    "complete source ledgers, recipient/receipt chain and exact relation to the report presented remain open": "Siguen abiertos los libros fuente completos, la cadena de destinatario/recepción y la relación exacta con el informe presentado",
    "source ledgers, formula verification, exact final/presented version and complete recipient chain remain open": "Siguen abiertos los libros fuente, la verificación de fórmulas, la versión final/presentada exacta y la cadena completa de destinatarios",
    "direct AC receipt/adoption, attachment hash/version identity and complete downstream use remain open": "Siguen abiertas la recepción/adopción directa por la AC, la identidad hash/versión del adjunto y el uso posterior completo",
    "full native chain, exact senders/recipients, intended report, actual AC meeting and adoption remain open": "Siguen abiertas la cadena nativa completa, los remitentes/destinatarios exactos, el informe previsto, la reunión real con la AC y la adopción",
    "which physical report/version was delivered, when, to whom, receipt, mandate and use remain open": "Siguen abiertos qué informe/versión física se entregó, cuándo, a quién, su recepción, mandato y uso",
    "native revision/signature review, participants, authority and effective-operation evidence remain open": "Siguen abiertas la revisión nativa de revisiones/firmas, los participantes, la autoridad y la prueba de explotación efectiva",
    "native messages, attachments, sender/recipient capacities, delivery, receipt and public-safe editions remain open": "Siguen abiertos los mensajes nativos, los adjuntos, las capacidades de remitentes/destinatarios, la entrega, la recepción y las ediciones aptas para publicación",
    "source comparison, morosity-vote issue, proxies, annexes, official book and implementation remain open": "Siguen abiertas la comparación de fuentes, la cuestión morosidad-voto, los poderes, los anexos, el libro oficial y la ejecución",
    "variants, audio, debt/vote basis, security contract, instructions, key/lock logs and unit reach remain open": "Siguen abiertas las variantes, el audio, la base deuda/voto, el contrato de seguridad, las instrucciones, los registros de llaves/cerraduras y el alcance por unidades",
    "manual line verification, official book/audio, annexes, notice/service and implementation remain open": "Siguen abiertas la verificación manual línea por línea, el libro oficial/audio, los anexos, la convocatoria/notificación y la ejecución",
    "native headers, recipient capacity, attachment hashes, acknowledgement, reply and downstream use remain open": "Siguen abiertas las cabeceras nativas, la capacidad del destinatario, los hashes de adjuntos, el acuse de recibo, la respuesta y el uso posterior",
    "original notice, ACTA, attendance, vote, budgets, annexes, circulation and implementation all remain open": "Siguen abiertas la convocatoria original, el ACTA, la asistencia, el voto, los presupuestos, los anexos, la circulación y la ejecución",
    "instructions, service, contracts, security/locksmith logs, affected units, title/possession basis and certified proceedings remain open": "Siguen abiertas las instrucciones, la notificación, los contratos, los registros de seguridad/cerrajería, las unidades afectadas, la base de título/posesión y los procedimientos certificados",
    "certified act and exact relationship to any Community authority representation remain open": "Siguen abiertos el acto certificado y su relación exacta con cualquier representación de autoridad comunitaria",
    "complete provenance/intake, source-by-source reliance, procedural record and tax-secrecy review remain open": "Siguen abiertas la procedencia/entrada completa, el uso fuente por fuente, el registro procesal y la revisión de secreto tributario",
    "native/variant comparison, manual verification, audio, annexes, title, notice, proxies, conflicts, votes and payments remain open": "Siguen abiertas la comparación nativo/variante, la verificación manual, el audio, los anexos, el título, la convocatoria, los poderes, los conflictos, los votos y los pagos",
    "native headers, attachment hashes, direct versus indirect recipients, acknowledgement and downstream use remain open": "Siguen abiertas las cabeceras nativas, los hashes de adjuntos, los destinatarios directos frente a indirectos, el acuse y el uso posterior",
    "complete court-native file, exact holdings, service and source admitted remain open": "Siguen abiertos el expediente judicial nativo completo, los pronunciamientos exactos, la notificación y la fuente admitida",
    "complete certified record and exact source-by-source reliance remain open": "Siguen abiertos el registro certificado completo y el uso exacto fuente por fuente",
    "certified application, order, appeal, service and later/final status remain open": "Siguen abiertos la solicitud certificada, el auto, la apelación, la notificación y el estado posterior/final",
    "complete pleadings, evidence, judgment certification, appeals and preclusion analysis remain open": "Siguen abiertos los escritos completos, la prueba, la certificación de sentencia, las apelaciones y el análisis de preclusión",
    "filing-by-filing transmission, debt reconciliation, AC review, notice and judicial reliance remain open": "Siguen abiertas la transmisión escrito por escrito, la conciliación de deuda, la revisión de la AC, la convocatoria y el uso judicial",
    "instructions, actual scope, authority, excess, affected units and later court reliance remain open": "Siguen abiertas las instrucciones, el alcance real, la autoridad, el exceso, las unidades afectadas y el uso judicial posterior",
    "complete certified source and exact proposition adopted remain open; no civil/title/tourism adjudication inferred": "Siguen abiertas la fuente certificada completa y la proposición exacta adoptada; no se infiere decisión civil, de título ni turística",
    "title/authority supplied, exact recipients, verification, financing, payment and implementation remain open": "Siguen abiertos el título/autoridad aportados, los destinatarios exactos, la verificación, la financiación, el pago y la ejecución",
    "complete intake, each statement/document-to-adjustment bridge and Audiencia Nacional record remain open; 2022 sources did not originate 2020 selection": "Siguen abiertas la entrada completa, cada puente declaración/documento-ajuste y el registro de la Audiencia Nacional; las fuentes de 2022 no originaron la selección de 2020",
    "page count/hash, A/B equivalence and official-book comparison open": "Siguen abiertos el recuento/hash de páginas, la equivalencia A/B y la comparación con el libro oficial",
    "official-book comparison and complete annex/signature set open": "Siguen abiertas la comparación con el libro oficial y el conjunto completo de anexos/firmas",
    "execution, accession, finca scope, amendments and integrity fields open": "Siguen abiertas la formalización, la adhesión, el alcance por finca, las modificaciones y los campos de integridad",
    "original circulation, official book and annexes open": "Siguen abiertos la circulación original, el libro oficial y los anexos",
    "omitted-page/annex relationship and official book open": "Siguen abiertas la relación página omitida/anexo y el libro oficial",
    "date/body authentication, original book, annexes and 15 July relation open": "Siguen abiertas la autenticación de fecha/órgano, el libro original, los anexos y la relación con el 15 de julio",
    "provider-copy equivalence, notice, annexes and official book open": "Siguen abiertas la equivalencia de la copia del proveedor, la convocatoria, los anexos y el libro oficial",
    "provider-copy equivalence, accounts/annexes and official book open": "Siguen abiertas la equivalencia de la copia del proveedor, las cuentas/anexos y el libro oficial",
    "notice, proxy/audio, variants and official book open": "Siguen abiertas la convocatoria, el poder/audio, las variantes y el libro oficial",
    "second occurrence hash, content/order reconciliation and official book open": "Siguen abiertos el hash de la segunda aparición, la conciliación de contenido/orden y el libro oficial",
    "order/annotations, notice, audio, proxies and official book open": "Siguen abiertos el orden/anotaciones, la convocatoria, el audio, los poderes y el libro oficial",
    "A/C reconciliation, notice, audio, proxies and official book open": "Siguen abiertas la conciliación A/C, la convocatoria, el audio, los poderes y el libro oficial",
    "headers/hashes, order/annotations, source variants and official book open": "Siguen abiertas las cabeceras/hashes, el orden/anotaciones, las variantes fuente y el libro oficial",
    "competent authority, service, scope, reversal/termination and integrity fields open": "Siguen abiertas la autoridad competente, la notificación, el alcance, la revocación/terminación y los campos de integridad",
    "identity/scope, delivery, acceptance, voting use and full proxy denominator open": "Siguen abiertos la identidad/alcance, la entrega, la aceptación, el uso para votar y el denominador completo de poderes",
    "native/certified comparison, notice, annexes and implementation open": "Siguen abiertas la comparación nativo/certificado, la convocatoria, los anexos y la ejecución",
    "native revisions/signatures, same-size hash conflict and package-to-native mapping open": "Siguen abiertas las revisiones/firmas nativas, el conflicto de hash con igual tamaño y el mapeo paquete-nativo",
    "provider/annotated variants, annexes, audio, arithmetic and official book open": "Siguen abiertas las variantes del proveedor/anotadas, los anexos, el audio, la aritmética y el libro oficial",
    "manual verification, official book/audio/proxies and accounts open": "Siguen abiertas la verificación manual, el libro oficial/audio/poderes y las cuentas",
    "binary difference, official book/audio/proxies and accounts open": "Siguen abiertas la diferencia binaria, el libro oficial/audio/poderes y las cuentas",
    "same-size hash conflict, native revision/signature and package mapping open": "Siguen abiertos el conflicto de hash con igual tamaño, la revisión/firma nativa y el mapeo del paquete",
    "delivery/receipt, proxies, annexes and official book open": "Siguen abiertas la entrega/recepción, los poderes, los anexos y el libro oficial",
    "variants, audio, debt/vote basis, security contract and official book open": "Siguen abiertas las variantes, el audio, la base deuda/voto, el contrato de seguridad y el libro oficial",
    "manual verification, official book/audio, annexes and implementation open": "Siguen abiertas la verificación manual, el libro oficial/audio, los anexos y la ejecución",
    "binary difference, manual verification and official book/audio open": "Siguen abiertas la diferencia binaria, la verificación manual y el libro oficial/audio",
    "all original 2018 event sources and integrity fields unlocated": "No están localizadas ninguna de las fuentes originales del evento de 2018 ni sus campos de integridad",
    "native master, variants, notice, annexes, audio, title/proxies/votes open": "Siguen abiertos el maestro nativo, las variantes, la convocatoria, los anexos, el audio, el título/poderes/votos",
    "native master, all alternate relations/highlighting provenance and annexes open": "Siguen abiertos el maestro nativo, todas las relaciones alternativas, la procedencia del resaltado y los anexos",

    # Exact provenance translations (reader-facing Spanish cards).
    "located control source/derivative; public package status is governed by the linked event manifest": "Fuente/derivado de control localizado; el estado del paquete público se rige por el manifiesto enlazado del evento",
    "signed/stamped primary notice located": "Convocatoria primaria firmada/sellada localizada",
    "no Community ACTA located in the finite searched universe": "No se localizó ACTA comunitaria en el universo finito buscado",
    "located Drive/email custody family; package control hash verified": "Familia de custodia Drive/correo localizada; hash de control del paquete verificado",
    "primary instrument located; execution schedule incomplete": "Instrumento primario localizado; cuadro de formalización incompleto",
    "recovered four-page working copy; later filename/date issue preserved": "Copia de trabajo de cuatro páginas recuperada; se preserva la incidencia posterior de nombre de archivo/fecha",
    "referenced by ACTA/source family; standalone original not located": "Referido por el ACTA/la familia fuente; original autónomo no localizado",
    "located multi-copy source family; control copy publicly digitised": "Familia fuente multicopia localizada; copia de control digitalizada públicamente",
    "proposal annex/appointment language located within source family": "Anexo de propuesta/texto de nombramiento localizado dentro de la familia fuente",
    "later ACTA recital and connected litigation sources; complete native file open": "Mención posterior en ACTA y fuentes litigiosas conectadas; expediente nativo completo abierto",
    "contract source family located; executed original/schedules incomplete": "Familia fuente contractual localizada; original formalizado/anexos incompletos",
    "direct contemporaneous email and attachments located": "Correo contemporáneo directo y adjuntos localizados",
    "contemporaneous statement and circulation sources located": "Declaración contemporánea y fuentes de circulación localizadas",
    "appeal source located; certified complete first-instance/appeal package incomplete": "Fuente de apelación localizada; paquete certificado completo de primera instancia/apelación incompleto",
    "communication existence/metadata located; body/attachments not publicly reviewed": "Existencia/metadatos de la comunicación localizados; cuerpo/adjuntos no revisados públicamente",
    "direct notice/circulation chain and reply located": "Cadena directa de convocatoria/circulación y respuesta localizada",
    "three source variants located; control copy publicly digitised": "Tres variantes fuente localizadas; copia de control digitalizada públicamente",
    "direct contemporaneous email located": "Correo contemporáneo directo localizado",
    "direct notice/agenda/source-request chain located in email and Drive custody": "Cadena directa de convocatoria/orden del día/solicitud de fuente localizada en correo y custodia Drive",
    "communication located": "Comunicación localizada",
    "forwarded/direct copies located; original RFC822 chain incomplete": "Copias reenviadas/directas localizadas; cadena RFC822 original incompleta",
    "two 77-page binaries and partial packages preserved; control family publicly digitised": "Dos binarios de 77 páginas y paquetes parciales preservados; familia de control digitalizada públicamente",
    "native report and spreadsheet/email workstream located; formulas/source support incomplete": "Informe nativo y línea de hoja de cálculo/correo localizados; fórmulas/soporte fuente incompletos",
    "correspondence located": "Correspondencia localizada",
    "signed primary report located": "Informe primario firmado localizado",
    "native DOCX and review correspondence located": "DOCX nativo y correspondencia de revisión localizados",
    "verified direct contemporaneous email; establishes meeting date and same-day report use": "Correo contemporáneo directo verificado; acredita la fecha de reunión y el uso del informe ese mismo día",
    "contemporaneous follow-up located/referenced in correction record": "Seguimiento contemporáneo localizado/referido en el registro de correcciones",
    "primary correspondence located; supports that an executive report had earlier been delivered in Las Palmas": "Correspondencia primaria localizada; sustenta que un informe ejecutivo se había entregado antes en Las Palmas",
    "agreements/circulation custody and delivery metadata located": "Custodia de acuerdos/circulación y metadatos de entrega localizados",
    "control copy and variants located; public redacted digitisation": "Copia de control y variantes localizadas; digitalización pública redactada",
    "control copy and alternate binary located; public redacted digitisation": "Copia de control y binario alternativo localizados; digitalización pública redactada",
    "direct email and attachment families located": "Correo directo y familias de adjuntos localizados",
    "only a later recital in the 2022 ACTA is located": "Sólo se localiza una mención posterior en el ACTA de 2022",
    "ACTA links and separate DP 1132 sources exist; complete implementation chain missing": "Existen enlaces del ACTA y fuentes DP 1132 separadas; falta la cadena completa de ejecución",
    "separate judicial source family referenced; certified act and relationship incomplete": "Familia fuente judicial separada referida; acto certificado y relación incompletos",
    "controlled tax registers; tax secrecy and complete intake/reliance record apply": "Registros tributarios controlados; se aplican el secreto tributario y el registro completo de entrada/uso",
    "control copy and alternate variant located; public redacted digitisation": "Copia de control y variante alternativa localizadas; digitalización pública redactada",
    "direct correspondence and attachments located": "Correspondencia directa y adjuntos localizados",
    "later 2016 ACTA recital plus connected judicial records": "Mención posterior en ACTA de 2016 y registros judiciales conectados",
    "judicial source located; complete certified record incomplete": "Fuente judicial localizada; registro certificado completo incompleto",
    "controlled dossier records interim suspension; complete certified chain incomplete": "El expediente controlado consigna suspensión cautelar; cadena certificada completa incompleta",
    "judgment source located; complete litigation chain incomplete": "Fuente de sentencia localizada; cadena litigiosa completa incompleta",
    "mixed primary copies and later recitals; complete filing chain incomplete": "Copias primarias y menciones posteriores mixtas; cadena completa de presentación incompleta",
    "ACTA facial link and mixed judicial/implementation records located": "Enlace facial del ACTA y registros mixtos judiciales/de ejecución localizados",
    "judicial act located/referenced; complete source record incomplete": "Acto judicial localizado/referido; registro completo de fuente incompleto",
    "source family exists and later actors cite the meeting; complete reliance chain incomplete": "La familia fuente existe y actores posteriores citan la reunión; cadena completa de uso incompleta",
    "controlled tax record indicates multiple source types; full intake/reliance chain incomplete": "El registro tributario controlado indica varios tipos de fuente; cadena completa de entrada/uso incompleta",
    "located Drive copy A; relationship to copy B unresolved": "Copia A de Drive localizada; relación con la copia B no resuelta",
    "located five-page package control copy B": "Copia B de control del paquete de cinco páginas localizada",
    "primary CEXP cession/statutes instrument located": "Instrumento primario CEXP de cesión/estatutos localizado",
    "second separately hashed five-page capture": "Segunda captura de cinco páginas con hash separado",
    "third separately hashed five-page capture": "Tercera captura de cinco páginas con hash separado",
    "located nine-page later-transmission control copy": "Copia de control de transmisión posterior de nueve páginas localizada",
    "located six-page partial variant": "Variante parcial de seis páginas localizada",
    "recovered four-page email-attachment working copy": "Copia de trabajo de cuatro páginas adjunta a correo recuperada",
    "partial three-page sibling binary": "Binario hermano parcial de tres páginas",
    "located six-page copy A/control copy": "Copia A/de control de seis páginas localizada",
    "located transmitted six-page attachment family B": "Familia B transmitida de adjunto de seis páginas localizada",
    "third separately hashed six-page scan": "Tercer escaneo de seis páginas con hash separado",
    "located sixteen-page copy A": "Copia A de dieciséis páginas localizada",
    "located sixteen-page control copy B": "Copia B de control de dieciséis páginas localizada",
    "located transmitted attachment family C": "Familia C de adjunto transmitido localizada",
    "separately hashed PDF24/order-and-annotation variant": "Variante PDF24/de orden y anotación con hash separado",
    "located one-page proxy associated with notice": "Poder de una página asociado a la convocatoria localizado",
    "located twenty-one-page Owners' Community control copy": "Copia de control comunitaria de veintiuna páginas localizada",
    "located three-page CEXP working export; conversion conflicts preserved": "Exportación de trabajo CEXP de tres páginas localizada; conflictos de conversión preservados",
    "actual three-page public-package control binary": "Binario real de control del paquete público de tres páginas",
    "second 90,821-byte conversion; SHA differs from registered Drive export": "Segunda conversión de 90.821 bytes; su SHA difiere de la exportación Drive registrada",
    "located four-page procedural extract A": "Extracto procesal A de cuatro páginas localizado",
    "located four-page Bandama-labelled procedural extract B": "Extracto procesal B de cuatro páginas rotulado Bandama localizado",
    "located thirty-eight-page Drive/email control family C": "Familia C de control Drive/correo de treinta y ocho páginas localizada",
    "separately hashed 38-page annotated sibling": "Binario hermano anotado de 38 páginas con hash separado",
    "located controlling seventy-seven-page family A": "Familia A de control de setenta y siete páginas localizada",
    "located distinct seventy-seven-page family B": "Familia B distinta de setenta y siete páginas localizada",
    "located twenty-four-page partial package in family C": "Paquete parcial de veinticuatro páginas localizado en la familia C",
    "located forty-seven-page partial package in family C": "Paquete parcial de cuarenta y siete páginas localizado en la familia C",
    "located fifty-page partial package in family C": "Paquete parcial de cincuenta páginas localizado en la familia C",
    "separate two-page notice, not minutes": "Convocatoria separada de dos páginas; no es un ACTA",
    "located two-page CEXP working export; same-size hash conflict preserved": "Exportación de trabajo CEXP de dos páginas localizada; conflicto de hash con igual tamaño preservado",
    "actual two-page public-package control; SHA differs from registered Drive export": "Control real del paquete público de dos páginas; su SHA difiere de la exportación Drive registrada",
    "located thirteen-page control copy with separate delivery communication": "Copia de control de trece páginas localizada con comunicación de entrega separada",
    "located eight-page source A/control package source": "Fuente A/de control del paquete de ocho páginas localizada",
    "located nine-page ACTAS.zip-derived public-package control": "Control del paquete público de nueve páginas derivado de ACTAS.zip localizado",
    "located second nine-page binary; not the public-package control": "Segundo binario de nueve páginas localizado; no es el control del paquete público",
    "second partial eight-page sibling binary": "Segundo binario hermano parcial de ocho páginas",
    "located exact nine-page control source": "Fuente exacta de control de nueve páginas localizada",
    "located separate nine-page alternate binary": "Binario alternativo separado de nueve páginas localizado",
    "separate one-page notice, not minutes": "Convocatoria separada de una página; no es un ACTA",
    "only later recital in 2022 ACTA located; standalone 2018 source missing": "Sólo se localiza una mención posterior en el ACTA de 2022; falta la fuente autónoma de 2018",
    "located seven-page package control copy": "Copia de control del paquete de siete páginas localizada",
    "separate seven-page binary variant recorded in section 4": "Variante binaria separada de siete páginas registrada en la sección 4",
    "separately hashed seven-page highlighted sibling binary": "Binario hermano resaltado de siete páginas con hash separado",
    "private native/public-safe summary": "Nativo privado/resumen apto para publicación",
    "public metadata; no underlying ACTA located": "Metadatos públicos; ACTA subyacente no localizada",
    "private/restricted; public chronology summary only": "Privado/restringido; sólo resumen cronológico público",
    "distinct binary retained privately; public-safe metadata/relationship only; not included in the ACTA control-copy facsimile, source-page gallery or OCR text edition": "Binario distinto conservado privadamente; sólo metadatos/relación aptos para publicación; no incluido en el facsímil de la copia de control del ACTA, la galería de páginas fuente ni la edición textual OCR",
    "distinct notice binary retained privately; public-safe metadata/relationship only; not included in the linked ACTA control-copy facsimile, source-page gallery or OCR text edition": "Binario distinto de convocatoria conservado privadamente; sólo metadatos/relación aptos para publicación; no incluido en el facsímil enlazado de la copia de control del ACTA, la galería de páginas fuente ni la edición textual OCR",
    "public gap metadata/private or unlocated original": "Metadatos públicos de laguna/original privado o no localizado",
    "mixed private/public judicial derivatives": "Derivados judiciales privados/públicos mixtos",
    "public judicial derivative/private native sources": "Derivado judicial público/fuentes nativas privadas",
    "private derivative/public-safe gap summary": "Derivado privado/resumen de laguna apto para publicación",
    "public bilingual gap page/original unlocated": "Página bilingüe pública de laguna/original no localizado",
    "mixed private/public derivatives": "Derivados privados/públicos mixtos",
    "public judicial summary/private source": "Resumen judicial público/fuente privada",
    "mixed private/public insolvency records": "Registros concursales privados/públicos mixtos",
    "mixed private/public summaries": "Resúmenes privados/públicos mixtos",
    "private, partial or unlocated primary material; public bilingual gap/event page only": "Material primario privado, parcial o no localizado; sólo página pública bilingüe de laguna/evento",
}


def _translate_controlled_phrase(value: str) -> str:
    """Translate a source-specific sentence through the reviewed phrase table."""
    translated = value
    for english, spanish in sorted(PHRASE_ES.items(), key=lambda item: len(item[0]), reverse=True):
        pattern = rf"(?<!\w){re.escape(english)}(?!\w)"
        translated = re.sub(pattern, spanish, translated, flags=re.IGNORECASE)
    if translated == value:
        raise ValueError(f"Controlled phrase table made no localization change: {value!r}")
    return translated[0].upper() + translated[1:] if translated else translated


def localization_status(value: object, field: str) -> str:
    """Describe how a scalar/card value is localized."""
    if field not in LOCALIZED_FIELDS:
        raise KeyError(f"Unsupported localized field: {field}")
    if isinstance(value, dict) and ("es" in value or "en" in value):
        return "source-bilingual"
    if isinstance(value, list):
        return "composite-localized"
    if not isinstance(value, str):
        return "non-scalar-localized"
    if value in STABLE_NAMES_OR_TERMS:
        return "stable-name-or-term"
    if value in EXACT_ES:
        return "controlled-spanish-translation"
    if field in CONTROLLED_PHRASE_FIELDS:
        return "controlled-spanish-phrase-translation"
    return "uncontrolled-scalar"


def localize_document_value(value: object, locale: str, field: str) -> object:
    """Localize a document-card value without an implicit English fallback."""
    if field not in LOCALIZED_FIELDS:
        raise KeyError(f"Unsupported localized field: {field}")
    if isinstance(value, dict) and ("es" in value or "en" in value):
        selected = value.get(locale)
        if selected in (None, ""):
            raise ValueError(f"Bilingual {field} lacks explicit {locale} value")
        return selected
    if isinstance(value, list):
        return [localize_document_value(item, locale, field) for item in value]
    if not isinstance(value, str):
        return value
    if locale == "en":
        return value
    if locale != "es":
        raise ValueError(f"Unsupported locale: {locale}")
    if value in STABLE_NAMES_OR_TERMS:
        return value
    if value in EXACT_ES:
        return EXACT_ES[value]
    if field in CONTROLLED_PHRASE_FIELDS:
        return _translate_controlled_phrase(value)
    raise ValueError(f"No controlled Spanish localization for {field}: {value!r}")


def validate_scalar_coverage(documents: list[dict]) -> list[str]:
    errors: list[str] = []
    for document in documents:
        stable_id = document.get("stable_id", "<missing-document-id>")
        for field in LOCALIZED_FIELDS:
            value = document.get(field)
            try:
                localized = localize_document_value(value, "es", field)
            except (KeyError, ValueError) as exc:
                errors.append(f"{stable_id}/{field}: {exc}")
                continue
            status = localization_status(value, field)
            if status == "uncontrolled-scalar":
                errors.append(f"{stable_id}/{field}: uncontrolled scalar")
            if isinstance(value, str) and value not in STABLE_NAMES_OR_TERMS and localized == value:
                errors.append(f"{stable_id}/{field}: silent English fallback")
    return errors


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--continuity", type=Path, default=CONTINUITY)
    args = parser.parse_args()
    payload = json.loads(args.continuity.read_text(encoding="utf-8"))
    errors = validate_scalar_coverage(payload.get("documents", []))
    if errors:
        raise SystemExit("\n".join(f"ERROR: {error}" for error in errors))
    print(
        f"Controlled Spanish localization covers {len(payload.get('documents', []))} "
        "ACTA document records"
    )


if __name__ == "__main__":
    main()
